language: ruby
rvm:
- 2.2

cache: 
- bundler
- directories:
  - .asset-cache
  - _assets/bower
  - node_modules
  
env:
  global:
  - REPO=baharboutique/baharboutique.github.io
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
notifications:
  email: webmaster@baharboutique.com
  
before_install:
- sudo apt-get -qq update
- sudo apt-get -y install nodejs npm
- npm install -g bower

script:
- set -e
- bower install
- bundle exec jekyll build
- set +e
- bundle exec htmlproofer ./_site  --assume-extension --allow-hash-href --check-html --http-status-ignore 0
- cd _site
- touch .nojekyll
- git init
- git config user.name "Travis-CI"
- git config user.email "travis@baharboutique.com"
- git add .
- git commit -m "Deployed to Github Pages" >/dev/null
- git push --force --quiet "https://$GH_TOKEN@github.com/$REPO" master > /dev/null 2>&1

git:
  depth: 10
