title: Bahar Boutique Tesettür
description: ''
url: 'https://baharboutique.github.io'
locale: de_DE
timezone: Europe/Berlin
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
        - delicious
        - reddit
        - tumblr
        - buffer
        - vk
    limit: 'false'
    style: icons
defaults:
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
    -
        scope:
            path: ''
            type: categories
        values:
            layout: category_grid
            seo:
              type: SomeProducts
    -
        scope:
            path: ''
            type: products
        values:
            layout: product
            seo:
              type: Product
collections:
    products:
        output: true
        permalink: '/:path.html'
    categories:
        output: true
        permalink: '/:path.html'
mediaurl: _media
baseurl: /
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - bower.json
assets:
  digest: true
  js_compressor: true
  css_compressor: true
  sources:
    - _assets/bower
    - _assets/less
    - _assets/images
    - _assets/js
    - _media
