title: 'Bahar Boutique Tesettür'
url: https://baharboutique.com
enforce_ssl: baharboutique.com
locale: de_DE
timezone: Europe/Berlin
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
        - delicious
        - reddit
        - tumblr
        - buffer
        - vk
    limit: false
    style: icons
defaults:
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
    -
        scope:
            path: ''
            type: categories
        values:
            layout: category_grid
            seo:
                type: SomeProducts
    -
        scope:
            path: ''
            type: products
        values:
            layout: product
            seo:
                type: Product
    -
        scope:
            path: ''
            type: posts
        values:
            layout: blog_post
collections:
    products:
        output: true
        permalink: ':path.html'
    categories:
        output: true
        permalink: ':path.html'
mediaurl: _media
exclude:
    - vendor
    - Gemfile
    - Gemfile.lock
    - bower.json
assets:
    digest: true
    js_compressor: true
    css_compressor: true
    sources:
        - _assets/bower
        - _assets/less
        - _assets/images
        - _assets/js
        - _media
profiles:
    provider:
        - facebook
        - twitter
        - google
        - pinterest
    facebook: '//www.facebook.com/baharboutiquetesettuer'
    twitter: '//twitter.com/Baharboutique'
    google: '//plus.google.com/+BaharBoutiqueTesettürBremen'
    pinterest: '//de.pinterest.com/baharboutiquete'

comments:
    provider: '1'

address: 'Gröpelinger Heerstr. 213'
zipcity: '28239 Bremen'
country: 'Deutschland'
tel: '+49(0)421 39094188'
email: 'info@baharboutique.com'
