url: 'http://openshift-jbeta.codeanyapp.com'

assets:
  digest: true
  js_compressor: false
  css_compressor: false
  less:
    relative_urls: false
  sources:
    - _assets/bower
    - _assets/less
    - _assets/images
    - _assets/js
    - _media
exclude:
  - .asset-cache
mediaurl: _media
profiles:
    provider:
        - facebook
        - twitter
        - google
        - pinterest
    facebook: '//www.facebook.com/baharboutiquetesettuer'
    twitter: '//twitter.com/Baharboutique'
    google: '//plus.google.com/+BaharBoutiqueTesettürBremen'
    pinterest: '//de.pinterest.com/baharboutiquete'
    
address: 'Gröpelinger Heerstr. 213'
zipcity: '28239 Bremen'
country: 'Deutschland'
tel: '+49(0)421 39094188'
email: 'info@baharboutique.com'