title: 'Bahar Boutique Tesettür'
url: 'https://baharboutique.github.io'
permalink: none
locale: de_DE
timezone: Europe/Berlin
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
        - delicious
        - reddit
        - tumblr
        - buffer
        - vk
    limit: 'false'
    style: icons
defaults:
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
    -
        scope:
            path: ''
            type: categories
        values:
            layout: category
    -
        scope:
            path: ''
            type: products
        values:
            layout: product
collections:
    products:
        output: true
        permalink: '/:path.html'
    categories:
        output: true
        permalink: '/:path.html'
mediaurl: _media
baseurl: /
comments:
    provider: '1'
exclude:
    - vendor
    - Gemfile
    - Gemfile.lock
    - bower.json
relative_permalinks: 'false'
analytics:
    provider: google_analytics
    tracking_id: UA-77304209-1
profiles:
    provider:
        - facebook
        - twitter
        - google
        - pinterest
    facebook: 'https://www.facebook.com/baharboutiquetesettuer'
    twitter: 'https://twitter.com/Bahar_Boutique'
    google: 'https://plus.google.com/105140503278343271378'
    pinterest: 'https://de.pinterest.com/baharboutiquete/'
